### ISSUE TITLE
Setup USWDS styles centrally to avoid duplication

### ISSUE THREAD

**Issue by juliasolorzano** [18F/marigold#38] opened 2017-01-18 18:53 UTC
Refs #32

**Comment by line47** [comment] 2017-01-25 15:14
This is addressed in https://github.com/18F/marigold/pull/43

**Comment by line47** [comment] 2017-02-02 14:24
This is a duplicate of https://github.com/18F/marigold/issues/39.
Closing

**Closed as completed by line47** 2017-02-02 14:24 UTC
